# Simple workflow for deploying static content to GitHub Pages
name: No CSS Allowed

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: ["main"]

jobs:
    css_python_test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip

            - name: Run tests
              run: |
                  python no_style_test.py
              continue-on-error: false  # This ensures that if the script fails, the workflow fails
